# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	# Box
	config.vm.box = "ubuntu/trusty64"
	
	# Network
	config.vm.network :forwarded_port, guest: 8080, host: 7070

	# Set virtual memory
	config.vm.provider "virtualbox" do |vb|
	    vb.memory = "1024"
	    vb.gui = true
	end
	
	# Install Galaxy
	# TODO make a script for starting/stoping Galaxy as a service/daemon. Start automatically at startup of vm.
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "galaxyserver.yml"	
		ansible.sudo = true
	end

	# Start galaxy in daemon mode
	config.vm.provision :shell, privileged: false, path: "vagrant-run-galaxy.sh", run: "always"
end
