# -*- mode: ruby -*-
# vi: ft=ruby ts=2 et

Vagrant.configure(2) do |config|

	# Box
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "w4m"

	# Network
	config.vm.network :forwarded_port, guest: 8080, host: 8080

	# Set virtual memory
	config.vm.provider "virtualbox" do |vb|
	    vb.memory = "2048"
	end
	
	#config.vm.provision "docker"
	
	# Create a directory for conda deps closed to / to avoid placehold/placehold ...
	config.vm.provision :shell, privileged: true, path: "vagrant-install-conda.sh"

	# Install Galaxy
	# TODO make a script for starting/stoping Galaxy as a service/daemon. Start automatically at startup of vm.
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "galaxyserver.yml"	
		ansible.sudo = true
	end

	config.vm.provision "file", source: "../files4galaxy/config/tool_conf.xml", destination: "galaxy/config/tool_conf.xml"
	config.vm.provision "file", source: "../files4galaxy/config/tool_sheds_conf.xml", destination: "galaxy/config/tool_sheds_conf.xml"
	config.vm.provision "file", source: "../files4galaxy/config/dependency_resolvers_conf.xml", destination: "galaxy/config/dependency_resolvers_conf.xml"
	config.vm.provision "file", source: "../files4galaxy/static/welcome.html", destination: "galaxy/static/welcome.html"
	config.vm.provision "file", source: "../files4galaxy/static/W4M", destination: "galaxy/static/W4M"

	# Start galaxy in daemon mode
  if ! ENV['TOOL_LIST'].nil?
	    config.vm.provision :shell, privileged: false, path: "vagrant-run-galaxy.sh", args:"start", run: "always"

	    # Install Galaxy tools
	    config.vm.provision :shell, privileged: true, path: "swap_create.sh", args:"4096", run: "always"
	    config.vm.provision "ansible" do |ansible|
		    ansible.verbose = "v"
		    ansible.extra_vars = { 
    	      "galaxy_tools_tool_list" => ENV['TOOL_LIST'], 
    	    }
		    ansible.playbook = "tools.yml"	
	    end
	    config.vm.provision :shell, privileged: true, path: "swap_remove.sh", run: "always"
	    config.vm.provision :shell, privileged: true, path: "swap_create.sh", args:"1024", run: "always"

	    # ReStart galaxy in daemon mode
	    config.vm.provision :shell, privileged: false, path: "vagrant-run-galaxy.sh", args:"restart", run: "always"
  end

end
